### ISSUE TITLE
[BUG] The simulation-ram-paper is not working

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/matlab-examples#6]
**************************
### Code of Conduct
_By submitting this report you automatically agree that you've read and accepted the following conditions._ 
- Support for DQ Robotics is given voluntarily and it's not the developers' role to educate and/or convince anyone of their vision.
- Any possible response and its timeliness will be based on the relevance, accuracy, and politeness of a request and the following discussion.
- If a DQ Robotics member replies, the user must let them know if their response solves their issue or not. 
- Any suggestion/advice/request made by anyone, as well intentioned as they might be, might not be incorporated into DQ Robotics.
*************************

**Bug description**

@dqrobotics/developers 

Hi @bvadorno 

The example vrep/simulation-ram-paper/main_simulation_file.m is not working. The example implements the classes `LBR4pVrepRobot` and `YouBotVrepRobot.m`  using the class `DQ_SerialManipulator` (currently an abstract class) instead of `DQ_SerialManipulatorDH`.  On the other hand, both classes are already defined (and updated) in [dqrobotics/matlab](https://github.com/dqrobotics/matlab/tree/master/interfaces/vrep/robots). A solution would be to remove the classes `LBR4pVrepRobot` and `YouBotVrepRobot.m` from [dqrobotics/matlab-examples](https://github.com/dqrobotics/matlab-examples/tree/master/vrep/simulation-ram-paper), as proposed in #4.

Best regards, 

Juancho

**To Reproduce**

Run the [main_simulation_file.m](https://github.com/dqrobotics/matlab-examples/blob/master/vrep/simulation-ram-paper/main_simulation_file.m) script

*Output*

```shell
Error using DQ_SerialManipulator
Too many input arguments.

Error in LBR4pVrepRobot/kinematics (line 58)
            kin = DQ_SerialManipulator(LBR4p_DH_matrix,'standard');

Error in vrep_scene_dqcontroller (line 54)
lwr4  = lwr4_vreprobot.kinematics();

Error in main_simulation_file (line 50)
vrep_scene_dqcontroller(simulation_parameters);
```

**Environment:**
 - OS: [Windows 11 64 bits]
 - dqrobotics version (current master branch)
 - MATLAB version R2022b

**Comment by bvadorno** [comment]
Hi @juanjqo,

Owing to historical explanation, it's important to emphasize that this example is not working anymore because of library architecture updates. I accepted https://github.com/dqrobotics/matlab-examples/pull/4. Does the example run now?

Best wishes,
Bruno

**Comment by juanjqo** [comment]
Hi @bvadorno, the example is running now.

Thanks!

Best regards, 

Juancho
